server: 
  port: 7003
 
eureka: 
  #server:
    #enable-self-preservation: false #关闭eureka的自我保护机制 注意：但不推荐关闭自我保护模式
  instance:
    #单机hostname设置
    #hostname: localhost #eureka服务端的实例名称 
    #集群hostname设置(需要在C:\WINDOWS\system32\drivers\etc\hosts中配置)
    hostname: eureka7003.com
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机），这里可以用${xxx.xxx}，引用的是yml中的配置key
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机设置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群设置
       