server: 
  port: 9527
 
spring: 
  application:
    name: springcloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com #hosts 地址映射文件 myzuul.com
    prefer-ip-address: true 
 
 
zuul: 
  prefix: /cyjch #服务名称的前缀（可选）
  ignored-services: "*" #忽略所有的真实微服务名称  #也可以忽略一个服务名ignored-services: springcloud-provider-dept
  routes: 
    mydept.serviceId: springcloud-provider-dept #原有的项目名称application.yml中的spring.application.name
    mydept.path: /mydept/**                     #映射的虚拟项目名称
  
info:
  app.name: springcloud-zuul-gateway
  company.name: www.cyjch.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

